# Generated by Django 5.2.6 on 2025-09-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lostitem',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
